#
#            CheatCheck v1.0
#   	      Автор: Тимур
#   	   Телеграм: @tmrtrsvch
#
# /check <игрок> (cheatcheck.use) - Вызвать игрока на проверку
# /uncheck <игрок> (cheatcheck.use) - Отпустить игрока с проверки
#

messages:
  no_permission: "&#FF2900&lП&#FA2300&lр&#F41D00&lо&#EF1700&lв&#E91200&lе&#E40C00&lр&#DE0600&lк&#D90000&lа&7&l: &fУ Вас нет прав для выполнения данной команды"
  player_not_found: "&#FF2900&lП&#FA2300&lр&#F41D00&lо&#EF1700&lв&#E91200&lе&#E40C00&lр&#DE0600&lк&#D90000&lа&7&l: &fДанный игрок не найден"
  not_on_check: "&#FF2900&lП&#FA2300&lр&#F41D00&lо&#EF1700&lв&#E91200&lе&#E40C00&lр&#DE0600&lк&#D90000&lа&7&l: &fДанный игрок не на проверке"
  check_usage: "&#FF2900&lП&#FA2300&lр&#F41D00&lо&#EF1700&lв&#E91200&lе&#E40C00&lр&#DE0600&lк&#D90000&lа&7&l: &fИспользуйте: &x&0&0&f&f&0&0/check <игрок>"
  uncheck_usage: "&#FF2900&lП&#FA2300&lр&#F41D00&lо&#EF1700&lв&#E91200&lе&#E40C00&lр&#DE0600&lк&#D90000&lа&7&l: &fИспользуйте: &x&0&0&f&f&0&0/uncheck <игрок>"
  cannot_check_self: "&#FF2900&lП&#FA2300&lр&#F41D00&lо&#EF1700&lв&#E91200&lе&#E40C00&lр&#DE0600&lк&#D90000&lа&7&l: &fВы не можете вызвать себя на проверку"
  successful_check_sender: "&#FF2900&lП&#FA2300&lр&#F41D00&lо&#EF1700&lв&#E91200&lе&#E40C00&lр&#DE0600&lк&#D90000&lа&7&l: &fВы успешно вызвали на проверку игрока &x&0&0&f&f&0&0{player}"
  successful_check_target: "&#FF2900&lП&#FA2300&lр&#F41D00&lо&#EF1700&lв&#E91200&lе&#E40C00&lр&#DE0600&lк&#D90000&lа&7&l: &fВы были вызваны на проверку. Вы не можете двигаться"
  successful_uncheck_sender: "&#FF2900&lП&#FA2300&lр&#F41D00&lо&#EF1700&lв&#E91200&lе&#E40C00&lр&#DE0600&lк&#D90000&lа&7&l: &fВы успешно проверили игрока &x&0&0&f&f&0&0{player}"
  successful_uncheck_target: "&#FF2900&lП&#FA2300&lр&#F41D00&lо&#EF1700&lв&#E91200&lе&#E40C00&lр&#DE0600&lк&#D90000&lа&7&l: &fВы успешно успешно прошли проверку. Удачной игры!"
  cannot_use_commands: "&#FF2900&lП&#FA2300&lр&#F41D00&lо&#EF1700&lв&#E91200&lе&#E40C00&lр&#DE0600&lк&#D90000&lа&7&l: &fВы не можете использовать команды во время проверки"
  center_screen_message: "&#FF2900&lП&#FA2300&lр&#F41D00&lо&#EF1700&lв&#E91200&lе&#E40C00&lр&#DE0600&lк&#D90000&lа"
  center_screen_subtitle: "&fВы были вызваны на проверку на читы"
  center_screen_display_time: 100